@startuml

package node_modules <<Frame>> {
  class electron
  class fs
  class papaparse
  class jquery
  class chart_js
  class sweetalert2
  class popper
  class bootstrap
}

package vendor <<Frame>> {
  class RLadapter
  Class SVMadapter
  class regression
  class svm
}

package FileManager <<Frame>> {
  class CVSFile
  class JSONFile
}

package MVC <<Frame>> {
  class Model 
  class Controller
  class View
}

MVC ..> vendor
MVC ..> FileManager
MVC ..> node_modules

@enduml