@startuml GrafanaClasses


class Model{
    - data: GrafanaData
    - predictor: Predictor 
    - strategy: Strategy
    + setData(GrafanaData): GrafanaData
    + setPredictor(Predictor): void
    + predict(): number
    + writeInflux(): void

}


class EditorView implements Props{
    + getUploadFile(any): void
    + render(): any
}


interface Props{
    + predictor: Predictor

}
class MainView implements Props {
    + render(): any
    + const getStyle: any
}

class PanelCtrl implements Props {
    - model: Model
    - lv: number
    - time: Date
    + constructor(PanelProps)
    - setData(): void
    - setPredictor(): void
    - predict(): void
    - writeInflux(): void
    - update(): void
    - render(): any

}

PanelCtrl*--Model



@enduml