@startuml uc1
!include ../style.pu

actor :Utente: as A

rectangle "UC1 - Addestramento del sistema"{
  together {
    usecase (UC1.1) as "UC1.1\n Inserimento dati di allenamento"
    usecase (UC1.2) as "UC1.2\n Utiilzzo del predittore già addestrato"
    usecase (UC1.3) as "UC1.3\n Scelta del modello di machine learning\n"
    usecase (UC1.4) as "UC1.4\n Avvio dell'addestramento"
    usecase (UC1.5) as "UC1.5\n Salvataggio dei risultati ottenuti"
    usecase (UC17) as "UC17\n Visualizzazione messaggio di errore\n invalidazione dati file di addestramento"
    usecase (UC25) as "UC25\n  Visualizzazione messaggio di errore\n nel file del predittore allenato"
    usecase (UC6)
    usecase (UC7)
    usecase (UC8)
    usecase (UC9)
    usecase (UC10)
    usecase (UC11)
  }
}

:A: -- (UC1.1)
:A: -- (UC1.2)
:A: -- (UC1.3)
:A: -- (UC1.4)
:A: -- (UC1.5)

(UC1.1) <.. (UC17) : <<extends>>
(UC1.2) <.. (UC25) : <<extends>>
(UC1.3) <|-- (UC6)
(UC1.3) <|-- (UC7)
(UC1.3) <|-- (UC8)
(UC1.3) <|-- (UC9)
(UC1.3) <|-- (UC10)
(UC1.3) <|-- (UC11)

@enduml
