@startuml uc14
!include ../style.pu

actor :Utente: as A
actor :Grafana: as A1

rectangle "UC14 - Configurazione alert"{
  together {
    usecase (UC14.1) as "UC14.1\n Creazione alert"
    usecase (UC14.2) as "UC14.2\n Definizione soglia massimale"
  }
}

:A: -- (UC14.1)
:A: -- (UC14.2)
(UC14.1) -- :A1:
(UC14.2) -- :A1:

@endluml
