@startuml uc2
!include ../style.pu

skinparam RectangleFontSize 16

actor :Utente: as A
actor :Grafana: as A1

rectangle "UC2 - Addestramento del predittore in Grafana"{
  together {
    usecase (UC2.1) as "UC2.1\n Scelta del flusso di dati"
    usecase (UC2.2) as "UC2.2\n Scelta del modello"
}
    together {
    usecase (UC9) as "UC9\n Scelto modello Support Vector Machine"
    usecase (UC10) as "UC10\n Scelto modello regressione lineare"
    usecase (UC11) as "UC11\n Scelto modello regressione esponenziale"
    usecase (UC12) as "UC12\n Scelto modello regressione logaritmica"
    usecase (UC13) as "UC13\n Scelto modello rete neurale"
    usecase (UC14) as "UC14\n Scelto modello SVM adattata alla regressione"
  }
}

:A: -- (UC2.1)
:A: -- (UC2.2)

(UC2.1) --- :A1:

(UC2.2) <|--(UC9)
(UC2.2) <|--(UC10)
(UC2.2) <|--(UC11)
(UC2.2) <|--(UC12)
(UC2.2) <|- (UC13)
(UC2.2) <|- (UC14)

@enduml
