@startuml uc3
!include ../style.pu

actor :Utente: as A
actor :Grafana: as A1

rectangle "UC3 - Configurazione del plug-in per la predizione"{
  together {
  usecase (UC3.1) as "UC3.1\n Caricamento dei risultati"
  usecase (UC3.2) as "UC3.2\n Scelta dei nodi"
  usecase (UC3.3) as "UC3.3\n Visualizzazione della previsione"

  usecase (UC18)
  usecase (UC19)

  usecase (UC20)
  usecase (UC21)

  usecase (UC4)
  usecase (UC5)
  usecase (UC22)
  }
}

:A: -- (UC3.1)
:A: -- (UC3.2)
:A: -- (UC3.3)
(UC3.1) --- :A1:
(UC3.2) --- :A1:
(UC3.3) -- :A1:

(UC3.1) <. (UC18) : <<extends>>
(UC3.1) <.left. (UC19) : <<extends>>

(UC3.2) <. (UC20) : <<extends>>
(UC3.2) <. (UC21) : <<extends>>

(UC20)-[hidden]-(UC21)

(UC3.3) <. (UC22) : <<extends>>
(UC3.3) <|-left- (UC4)
(UC3.3) <|-up- (UC5)

(UC4)-[hidden]-(UC5)


@endluml
